
package trng.soapWS.temp1;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CustomersService", targetNamespace = "http://www.example.org/CustomersService/", wsdlLocation = "file:/C:/Users/User/eclipse-workspace/customerWS/src/main/resources/CustomersService.wsdl")
public class CustomersService_Service
    extends Service
{

    private final static URL CUSTOMERSSERVICE_WSDL_LOCATION;
    private final static WebServiceException CUSTOMERSSERVICE_EXCEPTION;
    private final static QName CUSTOMERSSERVICE_QNAME = new QName("http://www.example.org/CustomersService/", "CustomersService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("file:/C:/Users/User/eclipse-workspace/customerWS/src/main/resources/CustomersService.wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CUSTOMERSSERVICE_WSDL_LOCATION = url;
        CUSTOMERSSERVICE_EXCEPTION = e;
    }

    public CustomersService_Service() {
        super(__getWsdlLocation(), CUSTOMERSSERVICE_QNAME);
    }

    public CustomersService_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), CUSTOMERSSERVICE_QNAME, features);
    }

    public CustomersService_Service(URL wsdlLocation) {
        super(wsdlLocation, CUSTOMERSSERVICE_QNAME);
    }

    public CustomersService_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CUSTOMERSSERVICE_QNAME, features);
    }

    public CustomersService_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CustomersService_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CustomersService
     */
    @WebEndpoint(name = "CustomersServiceSOAP")
    public CustomersService getCustomersServiceSOAP() {
        return super.getPort(new QName("http://www.example.org/CustomersService/", "CustomersServiceSOAP"), CustomersService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CustomersService
     */
    @WebEndpoint(name = "CustomersServiceSOAP")
    public CustomersService getCustomersServiceSOAP(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.example.org/CustomersService/", "CustomersServiceSOAP"), CustomersService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CUSTOMERSSERVICE_EXCEPTION!= null) {
            throw CUSTOMERSSERVICE_EXCEPTION;
        }
        return CUSTOMERSSERVICE_WSDL_LOCATION;
    }

}
