
package trng.soapWS.temp1;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b14002
 * Generated source version: 2.2
 * 
 */
@WebService(name = "CustomersService", targetNamespace = "http://www.example.org/CustomersService/")
@SOAPBinding(parameterStyle = SOAPBinding.ParameterStyle.BARE)
@XmlSeeAlso({
    ObjectFactory.class
})
public interface CustomersService {


    /**
     * 
     * @param parameters
     * @return
     *     returns trng.soapWS.temp1.AddCustomerResponse
     */
    @WebMethod(operationName = "AddCustomer", action = "http://www.example.org/CustomersService/AddCustomer")
    @WebResult(name = "AddCustomerResponse", targetNamespace = "http://www.example.org/CustomerOperations", partName = "parameters")
    public AddCustomerResponse addCustomer(
        @WebParam(name = "AddCustomerRequest", targetNamespace = "http://www.example.org/CustomerOperations", partName = "parameters")
        AddCustomerRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns trng.soapWS.temp1.UpdateCustomerResponse
     */
    @WebMethod(operationName = "UpdateCustomer", action = "http://www.example.org/CustomersService/UpdateCustomer")
    @WebResult(name = "UpdateCustomerResponse", targetNamespace = "http://www.example.org/CustomerOperations", partName = "parameters")
    public UpdateCustomerResponse updateCustomer(
        @WebParam(name = "UpdateCustomerRequest", targetNamespace = "http://www.example.org/CustomerOperations", partName = "parameters")
        UpdateCustomerRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns trng.soapWS.temp1.DeleteCustomerResponse
     */
    @WebMethod(operationName = "DeleteCustomer", action = "http://www.example.org/CustomersService/DeleteCustomer")
    @WebResult(name = "DeleteCustomerResponse", targetNamespace = "http://www.example.org/CustomerOperations", partName = "parameters")
    public DeleteCustomerResponse deleteCustomer(
        @WebParam(name = "DeleteCustomerRequest", targetNamespace = "http://www.example.org/CustomerOperations", partName = "parameters")
        DeleteCustomerRequest parameters);

    /**
     * 
     * @param parameters
     * @return
     *     returns trng.soapWS.temp1.GetCustomerResponse
     */
    @WebMethod(operationName = "GetCustomer", action = "http://www.example.org/CustomersService/GetCustomer")
    @WebResult(name = "GetCustomerResponse", targetNamespace = "http://www.example.org/CustomerOperations", partName = "parameters")
    public GetCustomerResponse getCustomer(
        @WebParam(name = "GetCustomerRequest", targetNamespace = "http://www.example.org/CustomerOperations", partName = "parameters")
        GetCustomerRequest parameters);

}
